### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by swetlover** [DengSir/tdBag2#1]
非常感谢，目前有两个问题。
1、离线银行界面无法移动。
2、Lua错误：
"Interface\\AddOns\\tdBag2\\Localization\\deDE-德语.lua:8: nesting of [[...]] is deprecated near '['",
关于本地化文件的lua错误，以上只举例了德语，报错是针对中文以外的所有本地化语言的。
备注：使用的curse版本。

**Comment by DengSir** [comment]
1. 开启了系统面板是不能移动的
2. 问题还存在么?

**Comment by swetlover** [comment]
以上问题已解决，谢谢！
