### ISSUE TITLE
[Retail] Missing ItemButtons 

### ISSUE THREAD

**Issue by pngmn** [DengSir/tdBag2#17]
Hey,

I know this addon doesn't have retail support. I tried to make it work with my own fork (https://github.com/pngmn/tdBag2).
I don't expect an answer but I am just out of ideas to fix the following bug. So feel free to close this issue if you want.

It's working except for one thing, if the number of item slots is higher than 467 (only possible on retail I think), the slots 468+ are missing/hidden. I tested this with 3 characters and the number is always 467 and I can't figure out why it breaks after that.

Example:
Bankslots with Reagentbank: 338
Bagslots: 146
Total: 484
Missing: Total - 467 = 17

![](https://i.imgur.com/IeHRKQO.png)

After reopening the Bag frame it looks like this:

![](https://i.imgur.com/Vhreg2N.png)

**Comment by DengSir** [comment]
try to modify the file "Item.lua" line 77
'Button' to 'ItemButton' ?

**Comment by pngmn** [comment]
That works, thank you 👍
