### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Michigras** [DengSir/tdBag2#3]
Is there any function/frame I can hook to get noticed when the addon's bag frame is opened? The frame seems not to be named. Currently I check for _tdBag2MoneyFrame1_ to be shown but it is a bit hacky to do so since the frame is _nil_ until the inventory has been opened for the first time.
So I check for the presence of _tdBag2MoneyFrame1_ via onUpdate.

**Comment by DengSir** [comment]
Maybe you can hook like this:
```
    local Frame = tdBag2:GetClass('UI.Frame')
    local orig_Constructor = Frame.Constructor

    function Frame:Constructor(...)
        orig_Constructor(self, ...)

        print(self)
    end
```
