### ISSUE TITLE
1.4.0 off-line bank always empty

### ISSUE THREAD

**Issue by Road-block** [DengSir/tdBag2#7]
This is an issue that first appeared with the 1.3.0 update and removal of the BagBrother and LibItemCache dependencies.

It persists in 1.3.1.

I have visited the bank multiple times after updating to refresh the Cache.

It always shows empty when I try to view it remotely (by using the right-click on bag icon functionality)

Live Bank
![Livebank](https://user-images.githubusercontent.com/109839/72279047-f506f400-363d-11ea-926b-30bf85d6d1ca.png)
vs Offline Bank
![Offlinebank](https://user-images.githubusercontent.com/109839/72279080-0819c400-363e-11ea-88ae-1579abb65bff.png)

**Comment by DengSir** [comment]
I can't reproduce this problem, can you send me a list of the addons you used?

**Comment by Road-block** [comment]
I tested that it's not my own [tdBag2_Facade](https://www.curseforge.com/wow/addons/tdbag2_facade) or [BastionEPGP](https://www.curseforge.com/wow/addons/bastionepgp). 
I'll see about disabling everything to see if it works with no other addons at all.

If it works, I'll do a binary search and post back if I find which addon has a conflict if that's the issue.
Only inventory related addon I can think of that I have installed is [Armory (Classic)](https://www.curseforge.com/wow/addons/armory-classic)

It's strange that I have no Lua errors (I'm running BugGrabber + Bugger so I'd have noticed errors) the off-line bank is just always empty.

**Comment by Road-block** [comment]
No luck. 
Disabled every other addon except BugGrabber / Bugger and tdBag2 / tdPack2.
`enUS Client, 1.13.3 32887 Dec 19 2019 11303`

I'll try wiping out saved variables and re-visiting my mail / bank next see if it's an upgrade path issue.
I'll back them up before wiping so I can attach here if it's saved variables problem.

**Comment by Road-block** [comment]
Clearing out saved variables didn't help either, I'm stumped.

**Comment by DengSir** [comment]
Does your game have any lua errors?

**Comment by DengSir** [comment]
There is a possibility, the API GetRealmName return "nil" when the character login, the issue is happaned.

But my realm doesn't seem to happen, I still can't reproduce the issue.

I try to improve this issue in version 1.4.1. Can you help me test it? thank you very much!

**Comment by Road-block** [comment]
> I try to improve this issue in version 1.4.1. Can you help me test it? thank you very much!

1.4.1 fixed it for me good job 👍
