### ISSUE TITLE
Binding header TDBAG2 is defined more than once in Interface\AddOns\tdBag2\Bindings.xml

### ISSUE THREAD

**Issue by D34d3nd** [DengSir/tdBag2#8]
Date: 2020-02-12 16:38:06
ID: 1
Error occured in: Global
Count: 1
Message: AceLocale-3.0: tdBag2: Missing entry for 'TITLE_EQUIP'
Debug:
   tdBag2\Api.lua:104: in main chunk
Locals:
None
AddOns:
tdBag2, v1.6.0

**Comment by chkmyid** [comment]
Same issue ;-)

> 12x Binding header TDBAG2 is defined more than once in tdBag2\Bindings.xml

This message will be recreated after login. tdBag2 works normally.

**Comment by chkmyid** [comment]
Open the text editor with the enUS.lua file inside the Localization folder and check the code below.

```
--[[Translation missing --]]
--[[ L["TITLE_COD|r"] = ""--]] 
--[[Translation missing --]]
--[[ L["TITLE_EQUIP"] = ""--]]
```

Find this part and make the following changes to hide the error message(lines 83~84):
```
L["TITLE_COD"] = "%s's COD"
L["TITLE_EQUIP"] = "%s's Equip"
```

This can solve the problem.

**Comment by swetlover** [comment]
Also have this lua error
```Lua
6x Binding header TDBAG2 is defined more than once in tdBag2\Bindings.xml
```
